---
title: "shiny HGF-agent"
author: "Jesper Fischer Ehmsen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(shiny)
library(ggplot2)
library(shinythemes)
library(shinyWidgets)
library(here)

#input = data.frame(kappa = 1.4, theta = 0.3, omega = -2,Inital_prec2 = 4,Inital_mu2 = 0,Inital_mu3 = 0,Inital_prec3 = 4)

bias = c(0.5,rep(c(0.2,0.8),3),0.5)
trials = c(150,rep(c(20,30),3),150)

slider_params1 <- list(
  list("theta", "theta", -10, 10, -6, 0.1),
  list("omega", "omega:", -10, 10, -4, 0.1),
  list("kappa", "kappa:", 0, 3, 1, 0.1),
  list("Inital_prec2", "Inital_prec2", 0, 4, 1, 0.1),
  list("Inital_mu2", "Inital_mu2", -5, 5, 0, 0.1),
  list("Inital_mu3", "Inital_mu3", -5, 5, 0, 0.1),
  list("Inital_prec3", "Inital_prec3", 0, 4, 1, 0.1)
)


ui <- fluidPage(
  tabsetPanel(
    tabPanel("Page 1",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params1, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot", height = "750px"))
      )
    )))
  )
)


server <- function(input, output) {
 hgf = reactive({
    
    source(paste0(here(),"/assignment2/hgf_agent.R"))
    u = rm_agent(bias,trials)
    data = hgf_agent(u,input)
        
    q1 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3) %>% mutate(level = 1, mu2 = NA, sa2 = NA,mu3 = NA,sa3 = NA)
    q2 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3) %>% mutate(level = 2, mu1hat = NA, sa1hat = NA, mu3 = NA, sa3 = NA, u = NA)
    q3 = data %>% dplyr::select(u,trial,mu1hat,sa1hat,mu2,sa2,mu3,sa3) %>% mutate(level = 3, mu1hat = NA, sa1hat = NA,mu2 = NA, sa2 = NA, u = NA)
    
    q3 = rbind(q1,q2,q3)
    
    q3$level = as.factor(q3$level)
    
    return(q3)   
 })
 
 output$plot <- renderPlot({
    source(paste0(here(),"/assignment2/hgf_agent.R"))

    u = rm_agent(bias,trials)
    hgf() %>% mutate(level = factor(level, labels = c("Predictions","Expectations","Volatility")),level = factor(level, levels = c("Volatility", "Expectations","Predictions")),lower1 = mu1hat-sa1hat, upper1 = mu1hat+sa1hat, lower2 = mu2-sa2, upper2 = mu2+sa2, lower3 = mu3-sa3, upper3 = mu3+sa3) %>%
    ggplot(aes())+
    geom_line(data = data.frame(level = as.factor("Predictions"), x = 1:length(u), y = rep(bias,trials)),aes(x = 1:length(u), y = rep(bias,trials)))+
    facet_wrap(~level, scales = "free",nrow = 3)+
    geom_line(aes(x = trial, y = mu1hat), col = "#c44e52")+
    geom_point(aes(x = trial, y = u), col = "black")+
    geom_ribbon(aes(x = trial, ymax = upper1, ymin = lower1), fill = "#4c72b0", alpha = 0.5)+
    geom_ribbon(aes(x = trial, ymax = upper2, ymin = lower2), fill  = "#c44e52", alpha = 0.5)+
    #geom_ribbon(aes(x = trial, ymax = upper3, ymin = lower3), fill  = "black", alpha = 0.5)+
    geom_line(aes(x = trial, y = mu2), col = "#c44e52")+
    geom_line(aes(x = trial, y = mu3), col = "black")+
    theme_classic()+
    theme(text = element_text(size=12))+
    ylab(" ")
   
 })
 
  
}
shinyApp(ui = ui, server = server)

```

