---
title: "advanced cognitive modeling"
author: "jesper fischer ehmsen"
date: "2023-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

library()
```


## R Markdown


```{r}
#get the function to simulate two agents playing the matching pennies experiment
source("agents.R")

#different parameter settings for the game and agents:
#ntrials the number of times the agents play the game
ntrials = 120
#alpha1_l is the learning rate for the first agent (matcher) when losing
alpha1_l = 1
#alpha1_l is the learning rate for the first agent (matcher) when winning
alpha1_w = 0.5
#alpha2_l is the learning rate for the first agent (non-matcher) when losing
alpha2_l = 0.5
#alpha1_l is the learning rate for the first agent (non-matcher) when winning
alpha2_w = 1
#bias1 is the bias of the first participant to answer 1. That is if it is 1 then agent 1 will choose 1 on the first trial, if 0.5 he picks at random
bias1 = 1
#bias 2 is what bias1 is for agent2
bias2 = 1

#the incentive of the first agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive1 = 0
#the incentive of the second agent do you play after your belief (0) or do you choose the oppisite of your belief (1)
incentive2 = 0


#different agents:
#random bias:
#to initialize a random bias agent the learning rates for that agent just have to set to 0 and the bias is will then determine the bias of the agent:

#win stay lose shift (WSLS):
#to initialize a (WSLS) agent the two learning rates for the agent has to be set to 1.

#rescorla wagner(RW) learner with constant learning rate
#to initialize this RW agent the two learning rates for the agent just have to be equal

#rescorla wagner(RW) learner with different learning rate for wins and loses
#to initialize a RW agent the two learning rates for the agent just have to be different:




df = rw_vs_rw(ntrials = ntrials,
         alpha1_l = alpha1_l,
         alpha1_w = alpha1_w,
         alpha2_l = alpha2_l,
         alpha2_w = alpha2_w,
         bias1 = bias1,
         bias2 = bias2,
         incentive1 = incentive1,  # 0 doesn't care about ,  1 does the oppisite
         incentive2 = incentive2
         )

df = data.frame(df)

plot_choices(df)

df1 = plot_cumwin(df)

df1$plot

```



```{r}

times = 100
agg = rw_vs_rw_times(times = times,
         ntrials = ntrials,
         alpha1_l = alpha1_l,
         alpha1_w = alpha1_w,
         alpha2_l = alpha2_l,
         alpha2_w = alpha2_w,
         bias1 = bias1,
         bias2 = bias2,
         incentive1 = incentive1,
         incentive2 = incentive2)

agg

agg %>% ggplot()+theme_classic()+
  geom_line(color = "red",aes(trials, meanrw1))+
  geom_line(color = "blue",aes(trials, meanrw2))+
  xlab("Trial")+
  ylab("Procent of wins")+
    ggtitle("Plot of Procent of wins of matcher (red) and non-matcher (blue)")+
  geom_ribbon(aes(x = trials, ymin = meanrw1-2*serw1, ymax = meanrw1+2*serw1, fill = "red"), alpha = 0.2)+
  geom_ribbon(aes(x = trials, ymin = meanrw2-2*serw2, ymax = meanrw2+2*serw2, fill = "blue"), alpha = 0.2)+
  scale_fill_manual(values = c("blue","red"), labels = c("matcher","nonmatcher"))+
  scale_color_manual(values = c("blue","red"), labels = c("matcher","nonmatcher"))

```


